apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  gateways:
    components:
      ingressGateway:
        k8s:
          nodeSelector:
            ingress-ready: "true"
          overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
            - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:80].hostPort
              value: 80
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Equal